"""Initial tables

Revision ID: 5b399588e07a
Revises: 
Create Date: 2024-04-28 02:33:18.706526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b399588e07a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserValues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('values', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserValues_id'), 'UserValues', ['id'], unique=False)
    op.create_index(op.f('ix_UserValues_telegram_id'), 'UserValues', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserValues_telegram_id'), table_name='UserValues')
    op.drop_index(op.f('ix_UserValues_id'), table_name='UserValues')
    op.drop_table('UserValues')
    # ### end Alembic commands ###
